;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.3
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

(in-package :cl-alsaseq)



(cl:defconstant CEPH_OSD_TMAP_HDR #\h)

(cl:defconstant CEPH_OSD_TMAP_SET #\s)

(cl:defconstant CEPH_OSD_TMAP_CREATE #\c)

(cl:defconstant CEPH_OSD_TMAP_RM #\r)

(cl:defconstant LIBRADOS_VER_MAJOR 0)

(cl:defconstant LIBRADOS_VER_MINOR 69)

(cl:defconstant LIBRADOS_VER_EXTRA 0)

(cl:defconstant LIBRADOS_VERSION_CODE (cl:+ (cl:ash 0 16) (cl:ash 69 8) 0))

(cl:defconstant LIBRADOS_SUPPORTS_WATCH 1)

(cl:defconstant LIBRADOS_LOCK_FLAG_RENEW #x1)

(cl:defconstant LIBRADOS_CREATE_EXCLUSIVE 1)

(cl:defconstant LIBRADOS_CREATE_IDEMPOTENT 0)

(cl:defconstant LIBRADOS_OP_FLAG_EXCL 1)

(cl:defconstant LIBRADOS_OP_FLAG_FAILOK 2)

(defanonenum 
	(LIBRADOS_CMPXATTR_OP_EQ #.1)
	(LIBRADOS_CMPXATTR_OP_NE #.2)
	(LIBRADOS_CMPXATTR_OP_GT #.3)
	(LIBRADOS_CMPXATTR_OP_GTE #.4)
	(LIBRADOS_CMPXATTR_OP_LT #.5)
	(LIBRADOS_CMPXATTR_OP_LTE #.6))

(defanonenum 
	(LIBRADOS_OPERATION_NOFLAG #.0)
	(LIBRADOS_OPERATION_BALANCE_READS #.1)
	(LIBRADOS_OPERATION_LOCALIZE_READS #.2)
	(LIBRADOS_OPERATION_ORDER_READS_WRITES #.4)
	(LIBRADOS_OPERATION_IGNORE_CACHE #.8)
	(LIBRADOS_OPERATION_SKIPRWLOCKS #.16)
	(LIBRADOS_OPERATION_IGNORE_OVERLAY #.32))

(cffi:defcstruct rados_pool_stat_t
	(num_bytes :pointer)
	(num_kb :pointer)
	(num_objects :pointer)
	(num_object_clones :pointer)
	(num_object_copies :pointer)
	(num_objects_missing_on_primary :pointer)
	(num_objects_unfound :pointer)
	(num_objects_degraded :pointer)
	(num_rd :pointer)
	(num_rd_kb :pointer)
	(num_wr :pointer)
	(num_wr_kb :pointer))

(cffi:defcstruct rados_cluster_stat_t
	(kb :pointer)
	(kb_used :pointer)
	(kb_avail :pointer)
	(num_objects :pointer))

(cffi:defcfun ("rados_version" rados_version) :void
  (major :pointer)
  (minor :pointer)
  (extra :pointer))

(cffi:defcfun ("rados_create" rados_create) :int
  (cluster :pointer)
  (id :string))

(cffi:defcfun ("rados_create2" rados_create2) :int
  (pcluster :pointer)
  (clustername :string)
  (name :string)
  (flags :pointer))

(cffi:defcfun ("rados_create_with_context" rados_create_with_context) :int
  (cluster :pointer)
  (cct :pointer))

(cffi:defcfun ("rados_ping_monitor" rados_ping_monitor) :int
  (cluster :pointer)
  (mon_id :string)
  (outstr :pointer)
  (outstrlen :pointer))

(cffi:defcfun ("rados_connect" rados_connect) :int
  (cluster :pointer))

(cffi:defcfun ("rados_shutdown" rados_shutdown) :void
  (cluster :pointer))

(cffi:defcfun ("rados_conf_read_file" rados_conf_read_file) :int
  (cluster :pointer)
  (path :string))

(cffi:defcfun ("rados_conf_parse_argv" rados_conf_parse_argv) :int
  (cluster :pointer)
  (argc :int)
  (argv :pointer))

(cffi:defcfun ("rados_conf_parse_argv_remainder" rados_conf_parse_argv_remainder) :int
  (cluster :pointer)
  (argc :int)
  (argv :pointer)
  (remargv :pointer))

(cffi:defcfun ("rados_conf_parse_env" rados_conf_parse_env) :int
  (cluster :pointer)
  (var :string))

(cffi:defcfun ("rados_conf_set" rados_conf_set) :int
  (cluster :pointer)
  (option :string)
  (value :string))

(cffi:defcfun ("rados_conf_get" rados_conf_get) :int
  (cluster :pointer)
  (option :string)
  (buf :string)
  (len :pointer))

(cffi:defcfun ("rados_cluster_stat" rados_cluster_stat) :int
  (cluster :pointer)
  (result :pointer))

(cffi:defcfun ("rados_cluster_fsid" rados_cluster_fsid) :int
  (cluster :pointer)
  (buf :string)
  (len :pointer))

(cffi:defcfun ("rados_wait_for_latest_osdmap" rados_wait_for_latest_osdmap) :int
  (cluster :pointer))

(cffi:defcfun ("rados_pool_list" rados_pool_list) :int
  (cluster :pointer)
  (buf :string)
  (len :pointer))

(cffi:defcfun ("rados_cct" rados_cct) :pointer
  (cluster :pointer))

(cffi:defcfun ("rados_get_instance_id" rados_get_instance_id) :pointer
  (cluster :pointer))

(cffi:defcfun ("rados_ioctx_create" rados_ioctx_create) :int
  (cluster :pointer)
  (pool_name :string)
  (ioctx :pointer))

(cffi:defcfun ("rados_ioctx_destroy" rados_ioctx_destroy) :void
  (io :pointer))

(cffi:defcfun ("rados_ioctx_cct" rados_ioctx_cct) :pointer
  (io :pointer))

(cffi:defcfun ("rados_ioctx_get_cluster" rados_ioctx_get_cluster) :pointer
  (io :pointer))

(cffi:defcfun ("rados_ioctx_pool_stat" rados_ioctx_pool_stat) :int
  (io :pointer)
  (stats :pointer))

(cffi:defcfun ("rados_pool_lookup" rados_pool_lookup) :pointer
  (cluster :pointer)
  (pool_name :string))

(cffi:defcfun ("rados_pool_reverse_lookup" rados_pool_reverse_lookup) :int
  (cluster :pointer)
  (id :pointer)
  (buf :string)
  (maxlen :pointer))

(cffi:defcfun ("rados_pool_create" rados_pool_create) :int
  (cluster :pointer)
  (pool_name :string))

(cffi:defcfun ("rados_pool_create_with_auid" rados_pool_create_with_auid) :int
  (cluster :pointer)
  (pool_name :string)
  (auid :pointer))

(cffi:defcfun ("rados_pool_create_with_crush_rule" rados_pool_create_with_crush_rule) :int
  (cluster :pointer)
  (pool_name :string)
  (crush_rule_num :pointer))

(cffi:defcfun ("rados_pool_create_with_all" rados_pool_create_with_all) :int
  (cluster :pointer)
  (pool_name :string)
  (auid :pointer)
  (crush_rule_num :pointer))

(cffi:defcfun ("rados_pool_delete" rados_pool_delete) :int
  (cluster :pointer)
  (pool_name :string))

(cffi:defcfun ("rados_ioctx_pool_set_auid" rados_ioctx_pool_set_auid) :int
  (io :pointer)
  (auid :pointer))

(cffi:defcfun ("rados_ioctx_pool_get_auid" rados_ioctx_pool_get_auid) :int
  (io :pointer)
  (auid :pointer))

(cffi:defcfun ("rados_ioctx_pool_requires_alignment" rados_ioctx_pool_requires_alignment) :int
  (io :pointer))

(cffi:defcfun ("rados_ioctx_pool_required_alignment" rados_ioctx_pool_required_alignment) :pointer
  (io :pointer))

(cffi:defcfun ("rados_ioctx_get_id" rados_ioctx_get_id) :pointer
  (io :pointer))

(cffi:defcfun ("rados_ioctx_get_pool_name" rados_ioctx_get_pool_name) :int
  (io :pointer)
  (buf :string)
  (maxlen :unsigned-int))

(cffi:defcfun ("rados_ioctx_locator_set_key" rados_ioctx_locator_set_key) :void
  (io :pointer)
  (key :string))

(cffi:defcfun ("rados_ioctx_set_namespace" rados_ioctx_set_namespace) :void
  (io :pointer)
  (nspace :string))

(cffi:defcfun ("rados_objects_list_open" rados_objects_list_open) :int
  (io :pointer)
  (ctx :pointer))

(cffi:defcfun ("rados_objects_list_get_pg_hash_position" rados_objects_list_get_pg_hash_position) :pointer
  (ctx :pointer))

(cffi:defcfun ("rados_objects_list_seek" rados_objects_list_seek) :pointer
  (ctx :pointer)
  (pos :pointer))

(cffi:defcfun ("rados_objects_list_next" rados_objects_list_next) :int
  (ctx :pointer)
  (entry :pointer)
  (key :pointer))

(cffi:defcfun ("rados_objects_list_close" rados_objects_list_close) :void
  (ctx :pointer))

(cffi:defcfun ("rados_ioctx_snap_create" rados_ioctx_snap_create) :int
  (io :pointer)
  (snapname :string))

(cffi:defcfun ("rados_ioctx_snap_remove" rados_ioctx_snap_remove) :int
  (io :pointer)
  (snapname :string))

(cffi:defcfun ("rados_ioctx_snap_rollback" rados_ioctx_snap_rollback) :int
  (io :pointer)
  (oid :string)
  (snapname :string))

(cffi:defcfun ("rados_rollback" rados_rollback) :int
  (io :pointer)
  (oid :string)
  (snapname :string))

(cffi:defcfun ("rados_ioctx_snap_set_read" rados_ioctx_snap_set_read) :void
  (io :pointer)
  (snap :pointer))

(cffi:defcfun ("rados_ioctx_selfmanaged_snap_create" rados_ioctx_selfmanaged_snap_create) :int
  (io :pointer)
  (snapid :pointer))

(cffi:defcfun ("rados_ioctx_selfmanaged_snap_remove" rados_ioctx_selfmanaged_snap_remove) :int
  (io :pointer)
  (snapid :pointer))

(cffi:defcfun ("rados_ioctx_selfmanaged_snap_rollback" rados_ioctx_selfmanaged_snap_rollback) :int
  (io :pointer)
  (oid :string)
  (snapid :pointer))

(cffi:defcfun ("rados_ioctx_selfmanaged_snap_set_write_ctx" rados_ioctx_selfmanaged_snap_set_write_ctx) :int
  (io :pointer)
  (seq :pointer)
  (snaps :pointer)
  (num_snaps :int))

(cffi:defcfun ("rados_ioctx_snap_list" rados_ioctx_snap_list) :int
  (io :pointer)
  (snaps :pointer)
  (maxlen :int))

(cffi:defcfun ("rados_ioctx_snap_lookup" rados_ioctx_snap_lookup) :int
  (io :pointer)
  (name :string)
  (id :pointer))

(cffi:defcfun ("rados_ioctx_snap_get_name" rados_ioctx_snap_get_name) :int
  (io :pointer)
  (id :pointer)
  (name :string)
  (maxlen :int))

(cffi:defcfun ("rados_ioctx_snap_get_stamp" rados_ioctx_snap_get_stamp) :int
  (io :pointer)
  (id :pointer)
  (t_arg2 :pointer))

(cffi:defcfun ("rados_get_last_version" rados_get_last_version) :pointer
  (io :pointer))

(cffi:defcfun ("rados_write" rados_write) :int
  (io :pointer)
  (oid :string)
  (buf :string)
  (len :pointer)
  (off :pointer))

(cffi:defcfun ("rados_write_full" rados_write_full) :int
  (io :pointer)
  (oid :string)
  (buf :string)
  (len :pointer))

(cffi:defcfun ("rados_clone_range" rados_clone_range) :int
  (io :pointer)
  (dst :string)
  (dst_off :pointer)
  (src :string)
  (src_off :pointer)
  (len :pointer))

(cffi:defcfun ("rados_append" rados_append) :int
  (io :pointer)
  (oid :string)
  (buf :string)
  (len :pointer))

(cffi:defcfun ("rados_read" rados_read) :int
  (io :pointer)
  (oid :string)
  (buf :string)
  (len :pointer)
  (off :pointer))

(cffi:defcfun ("rados_remove" rados_remove) :int
  (io :pointer)
  (oid :string))

(cffi:defcfun ("rados_trunc" rados_trunc) :int
  (io :pointer)
  (oid :string)
  (size :pointer))

(cffi:defcfun ("rados_getxattr" rados_getxattr) :int
  (io :pointer)
  (o :string)
  (name :string)
  (buf :string)
  (len :pointer))

(cffi:defcfun ("rados_setxattr" rados_setxattr) :int
  (io :pointer)
  (o :string)
  (name :string)
  (buf :string)
  (len :pointer))

(cffi:defcfun ("rados_rmxattr" rados_rmxattr) :int
  (io :pointer)
  (o :string)
  (name :string))

(cffi:defcfun ("rados_getxattrs" rados_getxattrs) :int
  (io :pointer)
  (oid :string)
  (iter :pointer))

(cffi:defcfun ("rados_getxattrs_next" rados_getxattrs_next) :int
  (iter :pointer)
  (name :pointer)
  (val :pointer)
  (len :pointer))

(cffi:defcfun ("rados_getxattrs_end" rados_getxattrs_end) :void
  (iter :pointer))

(cffi:defcfun ("rados_omap_get_next" rados_omap_get_next) :int
  (iter :pointer)
  (key :pointer)
  (val :pointer)
  (len :pointer))

(cffi:defcfun ("rados_omap_get_end" rados_omap_get_end) :void
  (iter :pointer))

(cffi:defcfun ("rados_stat" rados_stat) :int
  (io :pointer)
  (o :string)
  (psize :pointer)
  (pmtime :pointer))

(cffi:defcfun ("rados_tmap_update" rados_tmap_update) :int
  (io :pointer)
  (o :string)
  (cmdbuf :string)
  (cmdbuflen :pointer))

(cffi:defcfun ("rados_tmap_put" rados_tmap_put) :int
  (io :pointer)
  (o :string)
  (buf :string)
  (buflen :pointer))

(cffi:defcfun ("rados_tmap_get" rados_tmap_get) :int
  (io :pointer)
  (o :string)
  (buf :string)
  (buflen :pointer))

(cffi:defcfun ("rados_exec" rados_exec) :int
  (io :pointer)
  (oid :string)
  (cls :string)
  (method :string)
  (in_buf :string)
  (in_len :pointer)
  (buf :string)
  (out_len :pointer))

(cffi:defcfun ("rados_aio_create_completion" rados_aio_create_completion) :int
  (cb_arg :pointer)
  (cb_complete :pointer)
  (cb_safe :pointer)
  (pc :pointer))

(cffi:defcfun ("rados_aio_wait_for_complete" rados_aio_wait_for_complete) :int
  (c :pointer))

(cffi:defcfun ("rados_aio_wait_for_safe" rados_aio_wait_for_safe) :int
  (c :pointer))

(cffi:defcfun ("rados_aio_is_complete" rados_aio_is_complete) :int
  (c :pointer))

(cffi:defcfun ("rados_aio_is_safe" rados_aio_is_safe) :int
  (c :pointer))

(cffi:defcfun ("rados_aio_wait_for_complete_and_cb" rados_aio_wait_for_complete_and_cb) :int
  (c :pointer))

(cffi:defcfun ("rados_aio_wait_for_safe_and_cb" rados_aio_wait_for_safe_and_cb) :int
  (c :pointer))

(cffi:defcfun ("rados_aio_is_complete_and_cb" rados_aio_is_complete_and_cb) :int
  (c :pointer))

(cffi:defcfun ("rados_aio_is_safe_and_cb" rados_aio_is_safe_and_cb) :int
  (c :pointer))

(cffi:defcfun ("rados_aio_get_return_value" rados_aio_get_return_value) :int
  (c :pointer))

(cffi:defcfun ("rados_aio_release" rados_aio_release) :void
  (c :pointer))

(cffi:defcfun ("rados_aio_write" rados_aio_write) :int
  (io :pointer)
  (oid :string)
  (completion :pointer)
  (buf :string)
  (len :pointer)
  (off :pointer))

(cffi:defcfun ("rados_aio_append" rados_aio_append) :int
  (io :pointer)
  (oid :string)
  (completion :pointer)
  (buf :string)
  (len :pointer))

(cffi:defcfun ("rados_aio_write_full" rados_aio_write_full) :int
  (io :pointer)
  (oid :string)
  (completion :pointer)
  (buf :string)
  (len :pointer))

(cffi:defcfun ("rados_aio_remove" rados_aio_remove) :int
  (io :pointer)
  (oid :string)
  (completion :pointer))

(cffi:defcfun ("rados_aio_read" rados_aio_read) :int
  (io :pointer)
  (oid :string)
  (completion :pointer)
  (buf :string)
  (len :pointer)
  (off :pointer))

(cffi:defcfun ("rados_aio_flush" rados_aio_flush) :int
  (io :pointer))

(cffi:defcfun ("rados_aio_flush_async" rados_aio_flush_async) :int
  (io :pointer)
  (completion :pointer))

(cffi:defcfun ("rados_aio_stat" rados_aio_stat) :int
  (io :pointer)
  (o :string)
  (completion :pointer)
  (psize :pointer)
  (pmtime :pointer))

(cffi:defcfun ("rados_watch" rados_watch) :int
  (io :pointer)
  (o :string)
  (ver :pointer)
  (handle :pointer)
  (watchcb :pointer)
  (arg :pointer))

(cffi:defcfun ("rados_unwatch" rados_unwatch) :int
  (io :pointer)
  (o :string)
  (handle :pointer))

(cffi:defcfun ("rados_notify" rados_notify) :int
  (io :pointer)
  (o :string)
  (ver :pointer)
  (buf :string)
  (buf_len :int))

(cffi:defcfun ("rados_set_alloc_hint" rados_set_alloc_hint) :int
  (io :pointer)
  (o :string)
  (expected_object_size :pointer)
  (expected_write_size :pointer))

(cffi:defcfun ("rados_create_write_op" rados_create_write_op) :pointer)

(cffi:defcfun ("rados_release_write_op" rados_release_write_op) :void
  (write_op :pointer))

(cffi:defcfun ("rados_write_op_set_flags" rados_write_op_set_flags) :void
  (write_op :pointer)
  (flags :int))

(cffi:defcfun ("rados_write_op_assert_exists" rados_write_op_assert_exists) :void
  (write_op :pointer))

(cffi:defcfun ("rados_write_op_cmpxattr" rados_write_op_cmpxattr) :void
  (write_op :pointer)
  (name :string)
  (comparison_operator :pointer)
  (value :string)
  (value_len :pointer))

(cffi:defcfun ("rados_write_op_omap_cmp" rados_write_op_omap_cmp) :void
  (write_op :pointer)
  (key :string)
  (comparison_operator :pointer)
  (val :string)
  (val_len :pointer)
  (prval :pointer))

(cffi:defcfun ("rados_write_op_setxattr" rados_write_op_setxattr) :void
  (write_op :pointer)
  (name :string)
  (value :string)
  (value_len :pointer))

(cffi:defcfun ("rados_write_op_rmxattr" rados_write_op_rmxattr) :void
  (write_op :pointer)
  (name :string))

(cffi:defcfun ("rados_write_op_create" rados_write_op_create) :void
  (write_op :pointer)
  (exclusive :int)
  (category :string))

(cffi:defcfun ("rados_write_op_write" rados_write_op_write) :void
  (write_op :pointer)
  (buffer :string)
  (len :pointer)
  (offset :pointer))

(cffi:defcfun ("rados_write_op_write_full" rados_write_op_write_full) :void
  (write_op :pointer)
  (buffer :string)
  (len :pointer))

(cffi:defcfun ("rados_write_op_append" rados_write_op_append) :void
  (write_op :pointer)
  (buffer :string)
  (len :pointer))

(cffi:defcfun ("rados_write_op_remove" rados_write_op_remove) :void
  (write_op :pointer))

(cffi:defcfun ("rados_write_op_truncate" rados_write_op_truncate) :void
  (write_op :pointer)
  (offset :pointer))

(cffi:defcfun ("rados_write_op_zero" rados_write_op_zero) :void
  (write_op :pointer)
  (offset :pointer)
  (len :pointer))

(cffi:defcfun ("rados_write_op_exec" rados_write_op_exec) :void
  (write_op :pointer)
  (cls :string)
  (method :string)
  (in_buf :string)
  (in_len :pointer)
  (prval :pointer))

(cffi:defcfun ("rados_write_op_omap_set" rados_write_op_omap_set) :void
  (write_op :pointer)
  (keys :pointer)
  (vals :pointer)
  (lens :pointer)
  (num :pointer))

(cffi:defcfun ("rados_write_op_omap_rm_keys" rados_write_op_omap_rm_keys) :void
  (write_op :pointer)
  (keys :pointer)
  (keys_len :pointer))

(cffi:defcfun ("rados_write_op_omap_clear" rados_write_op_omap_clear) :void
  (write_op :pointer))

(cffi:defcfun ("rados_write_op_set_alloc_hint" rados_write_op_set_alloc_hint) :void
  (write_op :pointer)
  (expected_object_size :pointer)
  (expected_write_size :pointer))

(cffi:defcfun ("rados_write_op_operate" rados_write_op_operate) :int
  (write_op :pointer)
  (io :pointer)
  (oid :string)
  (mtime :pointer)
  (flags :int))

(cffi:defcfun ("rados_aio_write_op_operate" rados_aio_write_op_operate) :int
  (write_op :pointer)
  (io :pointer)
  (completion :pointer)
  (oid :string)
  (mtime :pointer)
  (flags :int))

(cffi:defcfun ("rados_create_read_op" rados_create_read_op) :pointer)

(cffi:defcfun ("rados_release_read_op" rados_release_read_op) :void
  (read_op :pointer))

(cffi:defcfun ("rados_read_op_set_flags" rados_read_op_set_flags) :void
  (read_op :pointer)
  (flags :int))

(cffi:defcfun ("rados_read_op_assert_exists" rados_read_op_assert_exists) :void
  (read_op :pointer))

(cffi:defcfun ("rados_read_op_cmpxattr" rados_read_op_cmpxattr) :void
  (read_op :pointer)
  (name :string)
  (comparison_operator :pointer)
  (value :string)
  (value_len :pointer))

(cffi:defcfun ("rados_read_op_getxattrs" rados_read_op_getxattrs) :void
  (read_op :pointer)
  (iter :pointer)
  (prval :pointer))

(cffi:defcfun ("rados_read_op_omap_cmp" rados_read_op_omap_cmp) :void
  (read_op :pointer)
  (key :string)
  (comparison_operator :pointer)
  (val :string)
  (val_len :pointer)
  (prval :pointer))

(cffi:defcfun ("rados_read_op_stat" rados_read_op_stat) :void
  (read_op :pointer)
  (psize :pointer)
  (pmtime :pointer)
  (prval :pointer))

(cffi:defcfun ("rados_read_op_read" rados_read_op_read) :void
  (read_op :pointer)
  (offset :pointer)
  (len :pointer)
  (buf :string)
  (bytes_read :pointer)
  (prval :pointer))

(cffi:defcfun ("rados_read_op_exec" rados_read_op_exec) :void
  (read_op :pointer)
  (cls :string)
  (method :string)
  (in_buf :string)
  (in_len :pointer)
  (out_buf :pointer)
  (out_len :pointer)
  (prval :pointer))

(cffi:defcfun ("rados_read_op_exec_user_buf" rados_read_op_exec_user_buf) :void
  (read_op :pointer)
  (cls :string)
  (method :string)
  (in_buf :string)
  (in_len :pointer)
  (out_buf :string)
  (out_len :pointer)
  (used_len :pointer)
  (prval :pointer))

(cffi:defcfun ("rados_read_op_omap_get_vals" rados_read_op_omap_get_vals) :void
  (read_op :pointer)
  (start_after :string)
  (filter_prefix :string)
  (max_return :pointer)
  (iter :pointer)
  (prval :pointer))

(cffi:defcfun ("rados_read_op_omap_get_keys" rados_read_op_omap_get_keys) :void
  (read_op :pointer)
  (start_after :string)
  (max_return :pointer)
  (iter :pointer)
  (prval :pointer))

(cffi:defcfun ("rados_read_op_omap_get_vals_by_keys" rados_read_op_omap_get_vals_by_keys) :void
  (read_op :pointer)
  (keys :pointer)
  (keys_len :pointer)
  (iter :pointer)
  (prval :pointer))

(cffi:defcfun ("rados_read_op_operate" rados_read_op_operate) :int
  (read_op :pointer)
  (io :pointer)
  (oid :string)
  (flags :int))

(cffi:defcfun ("rados_aio_read_op_operate" rados_aio_read_op_operate) :int
  (read_op :pointer)
  (io :pointer)
  (completion :pointer)
  (oid :string)
  (flags :int))

(cffi:defcfun ("rados_lock_exclusive" rados_lock_exclusive) :int
  (io :pointer)
  (o :string)
  (name :string)
  (cookie :string)
  (desc :string)
  (duration :pointer)
  (flags :pointer))

(cffi:defcfun ("rados_lock_shared" rados_lock_shared) :int
  (io :pointer)
  (o :string)
  (name :string)
  (cookie :string)
  (tag :string)
  (desc :string)
  (duration :pointer)
  (flags :pointer))

(cffi:defcfun ("rados_unlock" rados_unlock) :int
  (io :pointer)
  (o :string)
  (name :string)
  (cookie :string))

(cffi:defcfun ("rados_list_lockers" rados_list_lockers) :pointer
  (io :pointer)
  (o :string)
  (name :string)
  (exclusive :pointer)
  (tag :string)
  (tag_len :pointer)
  (clients :string)
  (clients_len :pointer)
  (cookies :string)
  (cookies_len :pointer)
  (addrs :string)
  (addrs_len :pointer))

(cffi:defcfun ("rados_break_lock" rados_break_lock) :int
  (io :pointer)
  (o :string)
  (name :string)
  (client :string)
  (cookie :string))

(cffi:defcfun ("rados_mon_command" rados_mon_command) :int
  (cluster :pointer)
  (cmd :pointer)
  (cmdlen :pointer)
  (inbuf :string)
  (inbuflen :pointer)
  (outbuf :pointer)
  (outbuflen :pointer)
  (outs :pointer)
  (outslen :pointer))

(cffi:defcfun ("rados_mon_command_target" rados_mon_command_target) :int
  (cluster :pointer)
  (name :string)
  (cmd :pointer)
  (cmdlen :pointer)
  (inbuf :string)
  (inbuflen :pointer)
  (outbuf :pointer)
  (outbuflen :pointer)
  (outs :pointer)
  (outslen :pointer))

(cffi:defcfun ("rados_buffer_free" rados_buffer_free) :void
  (buf :string))

(cffi:defcfun ("rados_osd_command" rados_osd_command) :int
  (cluster :pointer)
  (osdid :int)
  (cmd :pointer)
  (cmdlen :pointer)
  (inbuf :string)
  (inbuflen :pointer)
  (outbuf :pointer)
  (outbuflen :pointer)
  (outs :pointer)
  (outslen :pointer))

(cffi:defcfun ("rados_pg_command" rados_pg_command) :int
  (cluster :pointer)
  (pgstr :string)
  (cmd :pointer)
  (cmdlen :pointer)
  (inbuf :string)
  (inbuflen :pointer)
  (outbuf :pointer)
  (outbuflen :pointer)
  (outs :pointer)
  (outslen :pointer))

(cffi:defcfun ("rados_monitor_log" rados_monitor_log) :int
  (cluster :pointer)
  (level :string)
  (cb :pointer)
  (arg :pointer))


